notifications:
  email:
    recipients:
      - jasuarez+mesa-travis@igalia.com
      - tanty+mesa-travis@igalia.com

language: python
cache: pip
matrix:
  include:
    - python: 2.7
      env: TOX_ENV="py27-{noaccel,accel-nix,streams}"
    - python: 3.4
      env: TOX_ENV="py34-{noaccel,accel-nix,streams}"
    - python: 3.5
      env: TOX_ENV="py35-{noaccel,accel-nix,streams}"
    - python: 3.6
      env: TOX_ENV="py36-{noaccel,accel-nix,streams}"
install:
    pip install tox
script:
    - tox -e $TOX_ENV
